---
name: Acme-ReturnValue
version: 0.01
author:
  - 'Thomas Klausner <domm@zsi.at>'
abstract: report interesting module return values
license: perl
resources:
  license: http://dev.perl.org/licenses/
provides:
  Acme::ReturnValue:
    file: lib/Acme/ReturnValue.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
