---
name: Acme-ReturnValue
version: 0.05
author:
  - 'Thomas Klausner <domm@cpan.at>'
abstract: report interesting module return values
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Archive::Any: 0.093
  Class::Accessor: 0.31
  PPI: 1.118
  Parse::CPAN::Packages: 2.26
build_requires:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  Acme::ReturnValue:
    file: lib/Acme/ReturnValue.pm
    version: 0.05
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
